name: Λνι's Blog
description: Coding, startups and ideas.
meta_description: Λνι's Blog. Coding, startups and ideas.
date: 2012
permalink: /:year/:month/:day/:title

markdown: kramdown
highlighter: rouge

logo: false
paginate: 15
baseurl: ""
domain_name: "zion.gq"
google_analytics: ""
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "/"
author: "Λνι"
